version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ctf
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nextjs:
    build: .
    container_name: nextjs_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:password@mysql:3306/ctf"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
